import type { GlobalAsset } from './assetTypes'

export const TOP_STOCKS: GlobalAsset[] = [
  { id: 'stock-aapl',  symbol: 'AAPL',  name: 'Apple Inc.',                    type: 'stock', currency: 'USD' },
  { id: 'stock-msft',  symbol: 'MSFT',  name: 'Microsoft Corp.',               type: 'stock', currency: 'USD' },
  { id: 'stock-nvda',  symbol: 'NVDA',  name: 'NVIDIA Corp.',                  type: 'stock', currency: 'USD' },
  { id: 'stock-amzn',  symbol: 'AMZN',  name: 'Amazon.com Inc.',               type: 'stock', currency: 'USD' },
  { id: 'stock-googl', symbol: 'GOOGL', name: 'Alphabet Inc. (Class A)',        type: 'stock', currency: 'USD' },
  { id: 'stock-meta',  symbol: 'META',  name: 'Meta Platforms Inc.',            type: 'stock', currency: 'USD' },
  { id: 'stock-tsla',  symbol: 'TSLA',  name: 'Tesla Inc.',                     type: 'stock', currency: 'USD' },
  { id: 'stock-brkb',  symbol: 'BRK.B', name: 'Berkshire Hathaway Inc.',        type: 'stock', currency: 'USD' },
  { id: 'stock-jpm',   symbol: 'JPM',   name: 'JPMorgan Chase & Co.',           type: 'stock', currency: 'USD' },
  { id: 'stock-v',     symbol: 'V',     name: 'Visa Inc.',                      type: 'stock', currency: 'USD' },
  { id: 'stock-unh',   symbol: 'UNH',   name: 'UnitedHealth Group Inc.',        type: 'stock', currency: 'USD' },
  { id: 'stock-xom',   symbol: 'XOM',   name: 'Exxon Mobil Corp.',              type: 'stock', currency: 'USD' },
  { id: 'stock-wmt',   symbol: 'WMT',   name: 'Walmart Inc.',                   type: 'stock', currency: 'USD' },
  { id: 'stock-ma',    symbol: 'MA',    name: 'Mastercard Inc.',                type: 'stock', currency: 'USD' },
  { id: 'stock-jnj',   symbol: 'JNJ',   name: 'Johnson & Johnson',              type: 'stock', currency: 'USD' },
  { id: 'stock-pg',    symbol: 'PG',    name: 'Procter & Gamble Co.',            type: 'stock', currency: 'USD' },
  { id: 'stock-avgo',  symbol: 'AVGO',  name: 'Broadcom Inc.',                  type: 'stock', currency: 'USD' },
  { id: 'stock-hd',    symbol: 'HD',    name: 'The Home Depot Inc.',             type: 'stock', currency: 'USD' },
  { id: 'stock-cvx',   symbol: 'CVX',   name: 'Chevron Corp.',                  type: 'stock', currency: 'USD' },
  { id: 'stock-abbv',  symbol: 'ABBV',  name: 'AbbVie Inc.',                    type: 'stock', currency: 'USD' },
  { id: 'stock-ko',    symbol: 'KO',    name: 'Coca-Cola Co.',                  type: 'stock', currency: 'USD' },
  { id: 'stock-pep',   symbol: 'PEP',   name: 'PepsiCo Inc.',                   type: 'stock', currency: 'USD' },
  { id: 'stock-mrk',   symbol: 'MRK',   name: 'Merck & Co. Inc.',               type: 'stock', currency: 'USD' },
  { id: 'stock-cost',  symbol: 'COST',  name: 'Costco Wholesale Corp.',          type: 'stock', currency: 'USD' },
  { id: 'stock-amd',   symbol: 'AMD',   name: 'Advanced Micro Devices Inc.',     type: 'stock', currency: 'USD' },
  { id: 'stock-nflx',  symbol: 'NFLX',  name: 'Netflix Inc.',                   type: 'stock', currency: 'USD' },
  { id: 'stock-dis',   symbol: 'DIS',   name: 'The Walt Disney Co.',             type: 'stock', currency: 'USD' },
  { id: 'stock-crm',   symbol: 'CRM',   name: 'Salesforce Inc.',                type: 'stock', currency: 'USD' },
  { id: 'stock-adbe',  symbol: 'ADBE',  name: 'Adobe Inc.',                     type: 'stock', currency: 'USD' },
  { id: 'stock-bac',   symbol: 'BAC',   name: 'Bank of America Corp.',           type: 'stock', currency: 'USD' },
  { id: 'stock-orcl',  symbol: 'ORCL',  name: 'Oracle Corp.',                   type: 'stock', currency: 'USD' },
  { id: 'stock-csco',  symbol: 'CSCO',  name: 'Cisco Systems Inc.',              type: 'stock', currency: 'USD' },
  { id: 'stock-intc',  symbol: 'INTC',  name: 'Intel Corp.',                    type: 'stock', currency: 'USD' },
  { id: 'stock-qcom',  symbol: 'QCOM',  name: 'Qualcomm Inc.',                  type: 'stock', currency: 'USD' },
  { id: 'stock-amat',  symbol: 'AMAT',  name: 'Applied Materials Inc.',          type: 'stock', currency: 'USD' },
  { id: 'stock-gs',    symbol: 'GS',    name: 'Goldman Sachs Group Inc.',        type: 'stock', currency: 'USD' },
  { id: 'stock-ms',    symbol: 'MS',    name: 'Morgan Stanley',                 type: 'stock', currency: 'USD' },
  { id: 'stock-cat',   symbol: 'CAT',   name: 'Caterpillar Inc.',               type: 'stock', currency: 'USD' },
  { id: 'stock-ba',    symbol: 'BA',    name: 'Boeing Co.',                     type: 'stock', currency: 'USD' },
  { id: 'stock-de',    symbol: 'DE',    name: 'Deere & Company',                type: 'stock', currency: 'USD' },
  { id: 'stock-tsm',   symbol: 'TSM',   name: 'Taiwan Semiconductor (ADR)',     type: 'stock', currency: 'USD' },
  { id: 'stock-lvmh',  symbol: 'MC.PA', name: 'LVMH Moët Hennessy',             type: 'stock', currency: 'EUR' },
  { id: 'stock-asml',  symbol: 'ASML',  name: 'ASML Holding N.V.',              type: 'stock', currency: 'EUR' },
  { id: 'stock-nov',   symbol: 'NOVO-B.CO', name: 'Novo Nordisk A/S',           type: 'stock', currency: 'EUR' },
  { id: 'stock-nesn',  symbol: 'NESN.SW', name: 'Nestlé S.A.',                  type: 'stock', currency: 'CHF' },
  { id: 'stock-roche', symbol: 'ROG.SW', name: 'Roche Holding AG',              type: 'stock', currency: 'CHF' },
  { id: 'stock-siemens', symbol: 'SIE.DE', name: 'Siemens AG',                  type: 'stock', currency: 'EUR' },
  { id: 'stock-sap',   symbol: 'SAP',   name: 'SAP SE',                         type: 'stock', currency: 'EUR' },
  { id: 'stock-9988',  symbol: '9988.HK', name: 'Alibaba Group',                type: 'stock', currency: 'USD' },
  { id: 'stock-700',   symbol: '0700.HK', name: 'Tencent Holdings',             type: 'stock', currency: 'USD' },
]
